const businessNames = [
    "YesAchievers",
    "Goalcraft",
    "ProfitPioneer",
    "NexusCore",
    "Elevolution",
    "Innoviary",
    "Trekwise",
    "Braventure",
    "Bubblit",
    "PulseCharge",
    "Clicknect",
    "ZenZest",
    "RideRev",
    "SnapSavor",
    "StellarSoul",
    "Quantum",
    "Zenitharian",
    "StyleQuest",
    "OptiSuccess",
    "Uplead",
    "WordBlaze",
    "BrandReclaim",
    "ContentCrafters",
    "TechTriggers",
    "Persuade360",
    "InfluenceRise",
    "Emailiope",
    "HavenHunt",
    "ImagineLands",
    "EpicHaven",
    "CrownKey",
    "SyncShare",
    "DazzloTech",
    "RuleFlex",
    "Enigma",
    "TechOptima",
    "Funkytech",
    "OpenOps",
    "ByteSage",
    "Awarewave",
    "SparkTech",
    "Proficitas",
    "Triumphtician",
    "SurgeShift",
    "EffortlessCoding",
    "Illuminate",
    "TechCuriosity",
    "Engineerenigma",
    "VelocityByte",
    "Resources",
    "Inventory",
    "Leverage",
    "Affairs",
    "Economy",
    "Occupation",
    "Ability",
    "Accept",
    "Account",
    "Action",
    "Activity",
    "MelonWorks",
    "WaterFresh",
    "JuicyMelon",
    "SweetRind",
    "RindCraft",
    "MelonBurst",
    "HydroMelon",
    "ZestyMelon",
    "RipeWave",
    "MelonMagic",
    "AquaMelon",
    "MelonDelight",
    "MelonCharm",
    "MelonWhirl",
    "MelonBreeze",
    "LushMelon",
    "MelonEssence",
    "PureMelon",
    "FreshMelon",
    "MelonMingle"
];

function getRandomItem(array) {
    const randomIndex = Math.floor(Math.random() * array.length);
    return array[randomIndex];
}

function generateRandomName() {
    const randomName = getRandomItem(businessNames);
    document.getElementById('name').textContent = randomName + ' ' + 'Limited';
}

document.getElementById('generate').addEventListener('click', generateRandomName);